---
- name: Un playbook muy muy sencillo
  # A quienes se les va a operar 
  hosts: web
  tasks:
    - name: Upgrade all packages
      ansible.builtin.yum:
       name: '*'
       state: latest
       become: true

    - name: "Telegram"
      community.general.telegram:
        token: '7849177175:AAEmmfMDS1-LMCsDyzW5T6PB9qHC1KHS-1g'
        api_args:
         chat_id: 425060386
         parse_mode: "markdown"
         text: "Resultado"
        

- name: Un playbook muy muy sencillo
  # A quienes se les va a operar 
  hosts: web
  tasks:
    - name: Dame un mensaje
      ansible.builtin.debug:
        msg: "Bienvenido al mundo de Ansible"
    
    - name: "Applying patches to the server"
      yum: name=kernel state=latest
      register: patch_update
      become: true

    - name: "Reiniciar solo si se hizo un cambio"
      ansible.builtin.reboot:
      when: patch_update is changed
