---
- name: Un playbook muy muy sencillo
  # A quienes se les va a operar 
  hosts: web
  tasks:
    - name: Upgrade all packages
      ansible.builtin.yum:
       name: '*'
       state: latest
       become: true

    - name: Send notify to Telegram
       telegram:
        token: '7849177175:AAEmmfMDS1-LMCsDyzW5T6PB9qHC1KHS-1g'
        chat_id: 425060386
        msg: Your precious application has been deployed CATS: https://example.com
        
