---
- name: Un playbook muy muy sencillo
  # A quienes se les va a operar 
  hosts: web
  tasks:
    - name: "Applying patches to the server"
    yum: name=kernel state=latest
    when: application_process_check.stdout == "Process is not running.\r\n" and ansible_distribution == "RedHat" 
    register: patch_update


