---
- name: Un playbook muy muy sencillo
  # A quienes se les va a operar 
  hosts: web
  tasks:
    - name: Upgrade all packages
      ansible.builtin.yum:
       name: '*'
       state: latest
       become: true

        - name: "Telegram"
      community.general.telegram:
        token: '7849177175:AAEmmfMDS1-LMCsDyzW5T6PB9qHC1KHS-1g'
        api_args:
          chat_id: 425060386
          parse_mode: "markdown"
          text: "This failed {{outer_item.key}} {{outer_item.value}}"
        
